### ISSUE TITLE
Using DateTime and setting 'duedate'

### ISSUE THREAD

**Issue by alvin-huang** [jenkinsci/jira-steps-plugin#28] opened 2017-05-10 22:07 UTC
Is there an example of how the DateTime object can be used for an issue and can we set a duedate? I am trying something like:
```
import org.joda.time.DateTime;
DateTime dt = new DateTime(2018, 3, 26, 0, 0, 0, 0);
def issue = [
                    fields: [
                              project: [id: 1],
                              summary: 'summary',
                              description: 'description',
                              components: [[name: 'component']],
                              assignee: [name: 'first.last'],
                              duedate: dt
                            ]
                  ]
```
but it does not work.

**Comment by alvin-huang** [comment] 2017-05-10 22:17
I think it is because it is not in IssueInput which calls FieldsInput https://github.com/jenkinsci/jira-steps-plugin/blob/master/src/main/java/org/thoughtslive/jenkins/plugins/jira/api/input/FieldsInput.java 

If this is the issue I can open a PR to add a duedate as an input.

**Comment by nrayapati** [comment] 2017-05-13 04:39
Yes, if you are trying to editIssue that the cause, but if you are trying to create new issue, jira doesn't support duedate as an input(Hope I am correct here, I remember testing this with 6.1.13 version), so I am afraid that if we make a change to that `FieldsInput` we are also changing the create issue step. 

My idea was to add another step, may be called `jiraUpdateIssueFields`, which would support adding or updating issue fields including custom fields.

**Comment by nrayapati** [comment] 2017-05-13 05:16
Just tried again creating new issue with duedate, I get following error. 

```groovy
error={"errorMessages":[],"errors":{"duedate":"Field 'duedate' cannot be set. It is not on the appropriate screen, or unknown."}}
```

**Comment by alvin-huang** [comment] 2017-05-13 17:09
This might be related to #9 then. We have a custom issue type called a `Deploy` which is similar to a `Story` but has the added parameter of a `duedate` (ie: when they want it in prod/dev/qa). 

Your error is because none of the default issue types require that field and the optional `duedate` field is hidden from the initial form. In my case, the `duedate` is a required parameter on the `Deploy` form so I get an error such as:

```Error Message: {"errorMessages":[],"errors":{"duedate":"Due Date is required."}}```

**Comment by nrayapati** [comment] 2017-05-18 00:41
Agree with you @alvin-huang we can just add all the fields to the DTO and let users take care of what can be sent based on their JIRA customization, this works for new issues for sure, I will need to check on how this works with edit issues as it may override the current values with empty when user s won't send anything. 

And #9 will also enable newIssue and editIssue steps to consider custom fields.

**Comment by alvin-huang** [comment] 2017-05-18 18:49
@nrayapati sounds good to me! Do you want to pull in all the fields to the DTO or I can do it if you are working on checking the edit issue overrides?

**Comment by nrayapati** [comment] 2017-05-20 23:52
@alvin-huang  I can quickly check `editIssue`, and if that is working we can change `IssueInput` on these steps to `Issue` class, so that all the existing fields (most of the fields are already defined in there) from `Fields` can be used to send as an input as well. 

I don't remember now, why exactly that chose different classes for input out output. But now it doesn't make sense. So we can use same classes. 

And yeah, custom fields need to be handled separately. Thanks.

**Comment by nrayapati** [comment] 2017-05-21 00:14
Awesome, `editIssue` works too, so we can now have the same classes for both the cases, while sending it as an input and while querying issue with `getIssue`. But yes, user's need to make appropriate changes before they send the 'getIssue' output back to `newIssue` or `editIssue` in case if they are reusing the output.

**Comment by nrayapati** [comment] 2017-05-21 00:15
I will issue a pull request soon.

**Comment by nrayapati** [comment] 2017-05-21 00:45
I merged this change with https://github.com/jenkinsci/jira-steps-plugin/pull/32. We should be able to use `duedate` now. Thanks for your inputs @alvin-huang.

**Closed by nrayapati** 2017-05-21 00:45 UTC
